# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/protocols/mrp/protobuf/ConfigureConnectionMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyatv.protocols.mrp.protobuf import ProtocolMessage_pb2 as pyatv_dot_protocols_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/protocols/mrp/protobuf/ConfigureConnectionMessage.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=pyatv/protocols/mrp/protobuf/ConfigureConnectionMessage.proto\x1a\x32pyatv/protocols/mrp/protobuf/ProtocolMessage.proto\"-\n\x1a\x43onfigureConnectionMessage\x12\x0f\n\x07groupID\x18\x01 \x01(\t:Q\n\x1a\x63onfigureConnectionMessage\x12\x10.ProtocolMessage\x18^ \x01(\x0b\x32\x1b.ConfigureConnectionMessage'
  ,
  dependencies=[pyatv_dot_protocols_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.DESCRIPTOR,])


CONFIGURECONNECTIONMESSAGE_FIELD_NUMBER = 94
configureConnectionMessage = _descriptor.FieldDescriptor(
  name='configureConnectionMessage', full_name='configureConnectionMessage', index=0,
  number=94, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_CONFIGURECONNECTIONMESSAGE = _descriptor.Descriptor(
  name='ConfigureConnectionMessage',
  full_name='ConfigureConnectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupID', full_name='ConfigureConnectionMessage.groupID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['ConfigureConnectionMessage'] = _CONFIGURECONNECTIONMESSAGE
DESCRIPTOR.extensions_by_name['configureConnectionMessage'] = configureConnectionMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigureConnectionMessage = _reflection.GeneratedProtocolMessageType('ConfigureConnectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURECONNECTIONMESSAGE,
  '__module__' : 'pyatv.protocols.mrp.protobuf.ConfigureConnectionMessage_pb2'
  # @@protoc_insertion_point(class_scope:ConfigureConnectionMessage)
  })
_sym_db.RegisterMessage(ConfigureConnectionMessage)

configureConnectionMessage.message_type = _CONFIGURECONNECTIONMESSAGE
pyatv_dot_protocols_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(configureConnectionMessage)

# @@protoc_insertion_point(module_scope)
